---
- name: Create AWS instance
  hosts: localhost
  connection: local
  gather_facts: False
  remote_user: ubuntu
 
  vars:
    region: us-west-2
    instance_type: t2.micro
    ami: ami-6e1a0117
    project_name: surgeon
    env: surgeon
  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ project_name }}_security_group"
        description: "{{ project_name }} security group"
        region: "{{ region }}"
        rules:
          - proto: all  # https
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: test_firewall

    - name: Create an EC2 key
      ec2_key:
        name: "{{ project_name }}-{{ env }}-key"
        region: "{{ region }}"
      register: ec2_key

    - name: Save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="/home/ubuntu/DevOps_Milestone4_Special/awskey.pem" mode=0600
      when: ec2_key.changed

    - name: Create an EC2 instance
      ec2:
        key_name: "{{ project_name }}-{{ env }}-key"
        region: "{{ region }}"
        group_id: "{{ test_firewall.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        count: 3
        vpc_subnet_id: subnet-c7d1738e
        assign_public_ip: yes
      register: ec2

    - name: Delete pre-existing inventory file if it exists
      file:
        path: /home/ubuntu/DevOps_Milestone4_Special/inventory
        state: absent
      ignore_errors: yes

    - name: Create inventory file
      file:
        path: /home/ubuntu/DevOps_Milestone4_Special/inventory
        mode: 0644
        state: touch

    - name: Add line in file
      lineinfile:
        path: /home/ubuntu/DevOps_Milestone4_Special/inventory
        insertafter: EOF
        line: '[servers]'

    - name: Add Host1
      lineinfile: path=/home/ubuntu/DevOps_Milestone4_Special/inventory insertafter=EOF line="{{ ec2.instances[0].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/DevOps_Milestone4_Special/awskey.pem private_ip={{ ec2.instances[0].private_ip }} public_ip={{ ec2.instances[0].public_ip }}" state=present

    - name: Add Host2
      lineinfile:  path=/home/ubuntu/DevOps_Milestone4_Special/inventory insertafter=EOF line="{{ ec2.instances[1].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/DevOps_Milestone4_Special/awskey.pem private_ip={{ ec2.instances[1].private_ip }} public_ip={{ ec2.instances[1].public_ip }}" state=present

    - name: Add Host3
      lineinfile: path=/home/ubuntu/DevOps_Milestone4_Special/inventory insertafter=EOF line="{{ ec2.instances[2].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/DevOps_Milestone4_Special/awskey.pem private_ip={{ ec2.instances[2].private_ip }} public_ip={{ ec2.instances[2].public_ip }}" state=present
     
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"  
